@startuml
state Start {
[*] --> Initialisieren : Programm gestartet
    Initialisieren : Repositories
    Initialisieren : Views
    Initialisieren : Modell
}

Initialisieren --> ZustandSTART : setze index_aktuelle_box auf 0
state "Titelliste aller Vokabeboxen => ZustandSTART" as ZustandSTART {
    ZustandSTART: Titel aller Vokabelboxen in einer Liste anzeigen
    TitelAllerVokabelboxenAnzeigen : index_aktuelle_box
    TitelAllerVokabelboxenAnzeigen : list[alle_boxen]
    TitelAllerVokabelboxenAnzeigen --> TitelAllerVokabelboxenAnzeigen : aendere index_aktuelle_box
}
ZustandSTART --> ZustandBoxinfo
ZustandSTART --> ZustandVeraenderLernuhr
ZustandSTART --> ZustandENDE

state ZustandENDE: Beendet das Programm

state "Boxinfo => ZustandBoxinfo" as ZustandBoxinfo {
    ZustandBoxinfo: - Die Infos zur augewaehlten Box anzeigen
    ZustandBoxinfo: - Veraender aktuelle Frageeinheit
    VokabelboxInfoAnzeigen --> VokabelboxInfoAnzeigen : Aendere aktuelle_frage
    VokabelboxInfoAnzeigen : index_aktuelle_box
    VokabelboxInfoAnzeigen : aktuelle_frage
    VokabelboxInfoAnzeigen : fuer alle Frageeinheiten die Lerninfos anzeigen
    AktualisiereInfoManager: Teste, ob Aktualisierung notwendig ist
    AktualisiereInfoManager --> VokabelboxInfoAnzeigen
}
ZustandBoxinfo --> ZustandSTART : zurueck zu Liste der Vokabelboxen
ZustandBoxinfo --> ZustandTesteVokabeln : fuehre Aktion auf aktuelle Box mit aktueller Frageeinheit aus
ZustandBoxinfo --> ZustandZeigeVokabelliste
ZustandBoxinfo --> ZustandVeraenderLernuhr


ZustandTesteVokabeln --> AktualisiereInfoManager : abgebrochen
state "Vokabeln Testen => ZustandTesteVokabeln" as ZustandTesteVokabeln {
    ZustandTesteVokabeln --> ZustandTesteVokabeln : markieren
    VokabelkartePruefen: funktion = 'PRUEFEN'
    VokabelkartePruefen: karten =KartenfilterPruefen(karten_der_box)
    VokabelkarteLernen: funktion = 'LERNEN'
    VokabelkarteLernen: karten = KartenfilterLernen(karten_der_box)
    VokabelkarteNeu: funktion = 'NEU'
    VokabelkarteNeu: karten = KartenfilterNeu(karten_der_box)
}

    ZustandTesteVokabeln --> AktualisiereInfoManager : antworten mit 1 - 6 && Liste nicht leer
    ZustandTesteVokabeln --> AktualisiereInfoManager : antworten mit 1 - 6 && Liste leer || abgebrochen

ZustandZeigeVokabelliste : TODO
state "Zeige Vokabelliste" as ZustandZeigeVokabelliste {
    ZustandZeigeVokabelliste : Zeige die ausgweaehlte Vokabelliste mit verschiedenen Daten
    ZustandZeigeVokabelliste : Stats fuer jede Frageeinheit: ef, letzten 5, letzte Abfrage, naechste Abfrage
    ZeigeGesamteListe: Alle Karten der Box
    ZeigeLernListe: Alle Karten, die gelernt werden musssen
    ZeigeNeueListe: Liste der neuen Karten
}
ZustandZeigeVokabelliste --> ZustandEditorLerneinheit

ZustandEditorLerneinheit: TODO
state "Editor Lerneinheit" as ZustandEditorLerneinheit {
}
ZustandEditorLerneinheit --> ZustandZeigeVokabelliste
state Zustand_4: Pruefe, ob Liste noch zu pruefende Karten hat.

ZustandVeraenderLernuhr: Veraender Werte der Lernuhr
state "Veraender Lernuhr" as ZustandVeraenderLernuhr {
    EditorLernuhr: aktuelle_uhrzeit
    EditorLernuhr: -neue_uhrzeit
    EditorLernuhr: -neue_uhr
    EditorLernuhr --> EditorLernuhr: veraender Werte
}
ZustandVeraenderLernuhr --> ZustandSTART: zurueck ohne Speichern
ZustandVeraenderLernuhr --> AktualisiereInfoManager: Veraenderungen speichern

@enduml